### ISSUE TITLE
Remove AlamofireImage

### ISSUE THREAD

**Issue by xaanimus** [cuappdev/campus-tour-ios#23]

**Comment by jhseung** [comment]
oo why?

**Comment by xaanimus** [comment]
Reduce compile time. Also when #22 caching is implemented AlamofieeImage will prob be redundant.

**Comment by jhseung** [comment]
If we're just caching the events data, isn't it simpler to use alamofireimage to cache the images that we're fetching using URLs?

**Comment by xaanimus** [comment]
yeah it is actually, I agree
