### ISSUE TITLE
Make all class options one event

### ISSUE THREAD

**Issue by acheng96** [cuappdev/campus-tour-ios#78]
All class options (regardless of college) should be put under one event. The event detail view will have the generic description and link to the Cornell schedule page for sign up.

**Comment by acheng96** [comment]
There are 8 composite events:
- A&S Class Visit Options
- AAP Class Visit Options
- CALS Class Visit Options
- ENG Class Visit Options
- HE Class Visit Options
- ILR Class Visit Options
- JCB Dyson School - Class Visit Options
- JCB Hotel School - Class Visit Options

**Comment by jhseung** [comment]
Do we have an idea of how we're going to display the class options differently?

**Comment by jhseung** [comment]
#98 7d4d5e6

We may look further into optimizing class options as we update the app
