### ISSUE TITLE
Just show static time

### ISSUE THREAD

**Issue by acheng96** [cuappdev/campus-tour-ios#83]
- Don't change the time to the user's phone configurations.
- Format with Cornell's time zone
- Always show 12-hour time

**Comment by xaanimus** [comment]
Is it ok if it shows 24/12 hour depending on the user's settings? Using the "hh:mm a" format doesn't display 12-hour unless the user's locale is 12-hour based

**Comment by jhseung** [comment]
Can't we check if hour is >12? Super hacky lul

**Comment by xaanimus** [comment]
I think it should be fine if we display 24hour style if the user put it that way in their settings though

**Comment by acheng96** [comment]
Fixed in ae6ef8a
