### ISSUE TITLE
Make college and type not nil in setEvents() for Data Manager

### ISSUE THREAD

**Issue by acheng96** [cuappdev/campus-tour-ios#90]
This will probably affect filtering @jhseung

**Comment by jhseung** [comment]
All the filtering is done by scanning the tags, so we actually don't need that `college` and `type` properties

**Comment by xaanimus** [comment]
Oh ok, we can close this then

**Comment by jhseung** [comment]
Unless setting it helps optimize search elsewhere?

**Comment by xaanimus** [comment]
I'm not sure but don't think it would @acheng96
